### ISSUE TITLE
Cookbook bootstrap NoMethodError: undefined method `property' for #<Class:0x000000035301a8>

### ISSUE THREAD

**Issue by SnufflesC137** [brint/wordpress-cookbook#77]
I went through the default.rb and the templates and they all seem to be in order but no matter what, I cannot bootstrap/install the cookbook in ubuntu (vagrant-ubuntu-trusty-64 3.13.0-133-generic) or Centos 7 (3.10.0-693.el7.x86_64) using Chef 13.5.3-1 

Any help is appreciated

Thanks

192.168.128.34 [2017-10-16T06:31:58+00:00] ERROR: Running exception handlers
192.168.128.34 [2017-10-16T06:31:58+00:00] ERROR: Exception handlers complete
192.168.128.34 [2017-10-16T06:31:58+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
192.168.128.34 Chef Client failed. 0 resources updated
192.168.128.34 [2017-10-16T06:31:58+00:00] ERROR: undefined method `property' for #<Class:0x000000030f9328>
192.168.128.34 [2017-10-16T06:31:58+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

chef-stacktrace.out

Generated at 2017-10-16 06:23:50 +0000
NoMethodError: undefined method `property' for #<Class:0x000000035301a8>
/var/chef/cache/cookbooks/rsyslog/resources/file_input.rb:19:in `class_from_file'
/usr/lib/ruby/vendor_ruby/chef/mixin/from_file.rb:42:in `class_eval'
/usr/lib/ruby/vendor_ruby/chef/mixin/from_file.rb:42:in `class_from_file'
/usr/lib/ruby/vendor_ruby/chef/resource/lwrp_base.rb:54:in `build_from_file'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:208:in `load_lwrp_resource'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:193:in `block in load_lwrps_from_cookbook'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:192:in `each'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:192:in `load_lwrps_from_cookbook'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:120:in `block in compile_lwrps'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:119:in `each'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:119:in `compile_lwrps'
/usr/lib/ruby/vendor_ruby/chef/run_context/cookbook_compiler.rb:72:in `compile'
/usr/lib/ruby/vendor_ruby/chef/run_context.rb:86:in `load'
/usr/lib/ruby/vendor_ruby/chef/client.rb:250:in `setup_run_context'
/usr/lib/ruby/vendor_ruby/chef/client.rb:498:in `do_run'
/usr/lib/ruby/vendor_ruby/chef/client.rb:199:in `block in run'
/usr/lib/ruby/vendor_ruby/chef/client.rb:193:in `fork'
/usr/lib/ruby/vendor_ruby/chef/client.rb:193:in `run'
/usr/lib/ruby/vendor_ruby/chef/application.rb:208:in `run_chef_client'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:312:in `block in run_application'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:304:in `loop'
/usr/lib/ruby/vendor_ruby/chef/application/client.rb:304:in `run_application'
/usr/lib/ruby/vendor_ruby/chef/application.rb:66:in `run'
/usr/bin/chef-client:25:in `<main>'

**Comment by HerbertBodner** [comment]
@SnufflesC137  I had the same issue when using `kitchen test`.
The problem is that this cookbook is outdated and only works with chef 12. 
So I configured kitchen to use chef 12 by specifying following in the `.kitchen.yml`:
```
driver_config:
  require_chef_omnibus: "12"
```

HTH
